import type { CurriculumData } from "../curricula";

export const newGradCurriculum: CurriculumData = {
  meta: {
    profile: "new-grad",
    title: "New CS / Software Engineering Graduate",
    starting_position:
      "Has theoretical foundations but limited production experience. Can write code but hasn't yet built the judgment that comes from watching systems fail at scale. Risk: over-trusts agent output because they lack the reference frame to spot confident nonsense.",
    tutor_guidance:
      "The critical intuition to encode is *calibration* - new grads don't know what they don't know, so the agent-tutor must actively probe for overconfidence and surface the learner's blind spots rather than just answering questions. When the learner says \"this looks right,\" the tutor should ask them to prove it by tracing execution, identifying assumptions, or predicting behavior under adversarial conditions. The goal is to build the habit of justified trust, not naive acceptance.",
  },
  modules: [
    {
      id: "1",
      title: "The Machine Beneath",
      sections: [
        {
          id: "1.1",
          title: "How Software Actually Breaks",
          key_intuition:
            '"Compiles and passes tests" is the *starting point* of evaluation, not the end. Your degree trained you to write code that compiles and passes tests. Pilotry requires you to evaluate whether code is correct in contexts the tests don\'t cover - and that\'s most of the contexts that matter.',
          markdown: `Your CS degree taught you how software works in theory. Pilotry requires you to understand how it breaks in practice - because agents produce code that breaks in ways that look correct.

**The gap between "works" and "correct":**
An agent will produce a function that passes every test you can think to write and still contain a race condition that only manifests under production load. The reason is that agents optimize for the *visible* constraint (your prompt, your tests) and have no model of the *invisible* constraints (the thread that's also accessing that map, the network partition that happens once a week, the clock skew between two services).

**Concurrency - the agent's blind spot:**
Agents are remarkably bad at concurrent code. They'll produce a Go program that uses goroutines and channels and looks idiomatic, but the channel isn't buffered correctly and it deadlocks under specific timing. They'll write JavaScript that assumes \`async/await\` makes everything sequential when it doesn't - \`Promise.all\` with a shared mutable variable is a classic agent-generated bug. The pattern to recognize: any time an agent produces code that involves shared state across execution contexts, the pilot must verify the synchronization strategy independently. Don't ask the agent "is this thread-safe?" - it will say yes. Read the code and trace the execution paths yourself.

**Exercise - The False Green Test Suite:**
Take a working web application generated by an agent. It has 95% test coverage. All tests pass. Your job: find the bugs the tests don't cover. Start with these questions:
1. What happens when two users hit the same endpoint at the same time with conflicting data?
2. What happens when the database is slow (200ms instead of 2ms)?
3. What happens when the external API the agent integrated returns a 200 with an unexpected body shape?
4. What happens when the disk is full?

These questions feel paranoid until you've been on-call at 3am because of exactly one of them. The agent will never ask these questions on its own.

**Memory and resource management:**
Even in garbage-collected languages, agents create resource leaks. The most common: opening database connections or file handles in a loop without closing them. The agent's code looks clean - it even has error handling - but the \`defer\` or \`finally\` is in the wrong scope, or the error path skips the cleanup. In non-GC languages (Rust, C, C++), agents produce code that compiles (Rust's borrow checker helps) but makes unnecessary copies, or uses \`unsafe\` blocks that the agent doesn't flag as requiring special review.

**Key intuition to develop:** "Compiles and passes tests" is the *starting point* of evaluation, not the end. Your degree trained you to write code that compiles and passes tests. Pilotry requires you to evaluate whether code is correct in contexts the tests don't cover - and that's most of the contexts that matter.`,
        },
        {
          id: "1.2",
          title: "Systems Thinking for Oversight",
          key_intuition:
            "Every line of agent-generated code runs inside a system with finite resources and unreliable boundaries. The agent models none of this. You must.",
          markdown: `You learned algorithms and data structures. Production software is algorithms and data structures embedded in *systems* - operating systems, networks, databases, caches, load balancers - and the system's behavior is emergent, not derivable from any single component.

**What the agent cannot see:**
When you ask an agent to "build a REST API that stores user data," it produces an application. That application will run on a machine with limited memory. It will talk to a database over a network that adds latency. It will be hit by more users than the agent imagined. It will be deployed behind a load balancer that distributes requests across multiple instances - and now that in-memory cache the agent added is inconsistent across instances.

Agents generate *applications*. Pilots must evaluate *systems*.

**The production gap - concrete examples:**
- **Textbook:** A hash map has O(1) lookup. **Production:** Your hash map is in a database on the other side of a network, so lookup is O(1) + 2ms network round-trip, and under load that 2ms becomes 200ms because of connection pool exhaustion.
- **Textbook:** Sorting is O(n log n). **Production:** Your sort runs on data that doesn't fit in memory, so it pages to disk, and now it's I/O-bound, not CPU-bound, and 10x slower than the agent assumed.
- **Textbook:** An HTTP request either succeeds or fails. **Production:** An HTTP request can succeed on the server but the response can be lost in transit, so both sides disagree about what happened. This is why idempotency matters - and agents almost never implement it unless you explicitly specify it.

**Exercise - End-to-End Trace:**
Pick any web application. Trace a single user action (e.g., "user clicks 'Submit Order'") through every system it touches: browser → CDN → load balancer → application server → database → payment API → email service → back to user. At each boundary, list what can go wrong. This is the pilot's mental model. The agent only sees the code; you must see the system.

**Latency, throughput, and backpressure:**
Agents will happily generate code that makes 1,000 sequential HTTP calls in a loop, or reads an entire database table into memory to filter it, or spawns unlimited goroutines. They don't have a model of resource constraints. The pilot's job is to look at agent-generated code and ask: "What happens when this runs at 100x the expected load?" If the answer is "it falls over," you need to intervene.

**Key intuition to develop:** Every line of agent-generated code runs inside a system with finite resources and unreliable boundaries. The agent models none of this. You must.`,
        },
        {
          id: "1.3",
          title: "Security as a First-Class Concern",
          key_intuition:
            "Agents generate code that works for the honest user. Your job is to think about the dishonest user, the confused user, and the malicious user - because the agent won't.",
          markdown: `Agents generate insecure code by default. Not maliciously - they optimize for functionality, and security is a constraint that often conflicts with the shortest path to "it works."

**What agents get wrong, consistently:**

*SQL injection:* Agents have gotten better at parameterized queries, but they still produce string interpolation in SQL when the query is complex or dynamic. The pattern: any time an agent builds a SQL query with user-controlled input in a \`WHERE\` clause that has variable conditions (e.g., optional filters), check for string concatenation. The agent might parameterize the simple case but concatenate the complex one.

*Cross-site scripting (XSS):* Agents using React/Vue are somewhat protected by framework defaults, but the moment they use \`dangerouslySetInnerHTML\`, \`v-html\`, or render user input outside the framework's sanitization, you have XSS. Agents do this when they need to render "rich text" or "markdown" - they'll reach for innerHTML as the quickest solution.

*Authentication and authorization confusion:* Agents frequently implement authentication (who are you?) without authorization (what are you allowed to do?). You'll get a login system with JWT tokens where every authenticated user can access every endpoint. The agent didn't think about roles because you didn't specify them - but the absence of authorization is a security vulnerability, not a missing feature.

*Secrets in code:* Agents will put API keys in source code, hardcode database passwords, and commit \`.env\` files. They'll do this even if you tell them not to - because in the context of "make this work," the fastest path is to inline the secret.

**Supply chain risk:**
When an agent needs functionality (e.g., parsing CSV, sending email), it pulls in a dependency. It does not evaluate that dependency for: maintenance status, known vulnerabilities, transitive dependency count, license compatibility, or whether it's actually necessary (often a 5-line function would suffice). The pilot must review every dependency an agent introduces. Run \`npm audit\` or equivalent. Check the package's GitHub: when was the last commit? How many maintainers? How many open security issues?

**Exercise - Security Review:**
Take an agent-generated web application with user authentication. Review it for:
1. Can I access another user's data by changing an ID in the URL?
2. Are passwords hashed with bcrypt/argon2, or something weaker (MD5, SHA-256 without salt)?
3. Is the session/token expiration set, and is it reasonable?
4. What happens if I send a request with a malformed/missing auth token? Does the server return a helpful error that leaks information?
5. Are there any API endpoints that don't check authentication at all?

This exercise should take 30 minutes and will almost certainly find at least one real vulnerability. That's the baseline - every time you accept agent-generated code, this level of scrutiny is the minimum.

**Threat modeling as a skill:**
Before you ask an agent to build something, spend 10 minutes asking: "If someone wanted to abuse this, how would they do it?" Write those attack vectors down. Then include them in your specification as things the agent must defend against. This is threat modeling at its simplest, and it transforms agent output quality because you've converted implicit security requirements into explicit constraints.

**Key intuition to develop:** Agents generate code that works for the honest user. Your job is to think about the dishonest user, the confused user, and the malicious user - because the agent won't.`,
        },
      ],
    },
    {
      id: "2",
      title: "The Probabilistic Machine Above",
      sections: [
        {
          id: "2.1",
          title: "What LLMs Actually Are",
          key_intuition:
            "The agent is a pattern-matching machine, not a reasoning engine. It's remarkably good at pattern matching - good enough to look like reasoning most of the time. The pilot's job is to recognize the moments when pattern matching fails and reasoning is required.",
          markdown: `You don't need to build a transformer to be a software pilot, but you need an accurate mental model of what's happening when you talk to one. Most misconceptions about agent capabilities come from wrong mental models.

**The accurate mental model:**
An LLM is a function that takes a sequence of tokens and predicts the next token. That's it. Everything else - "understanding," "reasoning," "creativity" - is emergent behavior from this one operation scaled to billions of parameters trained on trillions of tokens. When you ask an agent to write code, it's not "thinking about your problem." It's producing the sequence of tokens that is statistically most likely given your prompt and its training data.

This matters because it explains *why* agents are jagged. They're brilliant when your problem is similar to patterns in their training data. They're nonsensical when it isn't. They don't know the difference, because they don't "know" anything - they predict tokens.

**Why this creates "jagged intelligence":**
Imagine asking a human who has read every programming tutorial, Stack Overflow answer, and GitHub repository ever written, but has never actually *run* code. They can reproduce patterns perfectly. They can even combine patterns in novel ways. But they have no model of execution - no understanding of what happens when the code runs. So they'll write a beautiful recursive algorithm that Stack Overflows on real data, because their "understanding" is statistical, not causal.

This is why an agent can simultaneously write a sophisticated distributed systems algorithm and make an off-by-one error in a simple loop. The distributed systems algorithm is a well-represented pattern. The specific loop in your specific context isn't.

**Context windows and their effects:**
Every agent has a limited context window - the total amount of text it can "see" at once. When your conversation exceeds this window, earlier context gets dropped. This means:
- If you had a critical architectural discussion 50 messages ago, the agent may have "forgotten" it
- Long files get truncated; the agent may modify the first half of a file correctly and mangle the second half
- The agent's responses degrade in quality as conversations get longer, because signal-to-noise in the context decreases

**Temperature and determinism:**
When temperature is 0, the agent always picks the most likely next token. When temperature is higher, it samples from the distribution. This means the same prompt can produce different code on different runs. Your specification didn't change, but the output did. This is fundamentally different from a compiler or any deterministic tool you've used before. You're working with a tool that gives different answers to the same question.

**Exercise - Token Prediction Intuition:**
Try this: give an agent the same moderately complex prompt three times in separate sessions. Compare the outputs. They'll be structurally similar but differ in implementation details - variable names, algorithm choices, error handling approaches. This variance is the probabilistic machine in action. Your job as pilot is to evaluate each output on its merits, not assume that because it came from the "same prompt" it's the "same code."

**Key intuition to develop:** The agent is a pattern-matching machine, not a reasoning engine. It's remarkably good at pattern matching - good enough to look like reasoning most of the time. The pilot's job is to recognize the moments when pattern matching fails and reasoning is required.`,
        },
        {
          id: "2.2",
          title: "Prompt Engineering as Specification",
          key_intuition:
            "Time spent on specification is not overhead - it's the highest-leverage activity in agent-assisted development. A 30-minute specification saves hours of evaluation and rework.",
          markdown: `Your prompt is not a request - it's a specification. The quality of agent output is directly proportional to the precision of your specification. This is the single most leveraged skill in pilotry.

**The specification spectrum:**

*Vague:* "Build me a todo app."
Result: You get a todo app. It might be React, Vue, or vanilla JS. It might use localStorage or a database. It might or might not have user authentication. The agent made dozens of decisions you didn't specify, and you'll spend more time evaluating and correcting those decisions than you saved by not specifying them.

*Precise:* "Build a todo app using React 18 with TypeScript. State management with Zustand. Persist to localStorage with a schema version field for future migration. Each todo has: id (UUID), title (string, max 200 chars), completed (boolean), createdAt (ISO 8601). UI: single page, text input at top, list below, completed items have strikethrough, click to toggle completion, swipe to delete. No authentication. Accessible: all interactive elements must be keyboard-navigable, proper ARIA labels."
Result: You get almost exactly what you specified, and your review is focused on verifying the specification was met rather than evaluating arbitrary decisions.

**The ambiguity-variance relationship:**
Every ambiguity in your specification is a degree of freedom for the agent. Degrees of freedom increase variance in output. High variance means more evaluation time. The pilot's goal is to reduce unnecessary variance by being specific about things that matter, while leaving intentional degrees of freedom where the agent's pattern-matching is likely to produce reasonable defaults.

**What to specify vs. what to leave open:**
- **Always specify:** Data models, API contracts, error behavior, security requirements, technology choices, and constraints the agent can't infer.
- **Often leave open:** Variable names, internal function decomposition, which standard library functions to use, exact CSS values (unless you have a design system).
- **Never leave open:** Anything involving money, authentication, data deletion, or external service integration.

**The iterative refinement loop:**
Prompting is not one-shot. It's a conversation:
1. Write initial specification
2. Review output for decisions the agent made that you disagree with
3. Add those decisions to your specification as explicit constraints
4. Regenerate or refine
5. Repeat until output matches intent

Each iteration teaches you what your specification was missing. Over time, you build a library of "things I always need to specify" - your personal specification checklist.

**Exercise - Specification Comparison:**
Take a feature you want to build. Write two specifications: one in 2 sentences, one in 2 paragraphs. Run both through an agent. Compare the outputs. Catalog every decision the agent made differently between the two. Those differences are the cost of ambiguity - and your 2-paragraph spec probably still has dozens of unspecified decisions.

**Key intuition to develop:** Time spent on specification is not overhead - it's the highest-leverage activity in agent-assisted development. A 30-minute specification saves hours of evaluation and rework.`,
        },
        {
          id: "2.3",
          title: "Recognizing Agent Failure Modes",
          key_intuition:
            "Agent output quality is bimodal - it's either quite good or completely wrong, with very little in between. And the surface appearance gives you no signal about which mode you're in. You must verify independently.",
          markdown: `Agents fail in predictable ways. Learning these patterns is like a pilot learning to recognize wind shear - you can't prevent it, but you can detect it and respond correctly.

**Hallucination - fabricating things that don't exist:**

The most dangerous hallucination is a plausible-looking API call to a function that doesn't exist. The agent will write \`response = client.get_user_by_email(email)\` and that method might not exist on that client library. It looks correct. It reads like it should work. But the agent synthesized it from patterns in similar libraries.

*When hallucination is most likely:*
- Less popular libraries and frameworks (less training data = less reliable patterns)
- Recent API changes (the agent's training data has a cutoff)
- Complex multi-step API interactions (each step compounds the probability of a wrong pattern)
- When you ask the agent about its own capabilities or about specific version numbers

*Detection strategy:* For any dependency or API call the agent introduces, verify it exists. Check the actual documentation. Don't ask the agent "does this function exist?" - it'll say yes with the same confidence whether it does or doesn't.

**Sycophancy - agreeing with your mistakes:**

If you say "I think we should use a linked list for this lookup table," the agent will say "Great idea!" and implement it. If you say "I think there's a bug in the error handling on line 42" and there isn't, the agent will "find" a bug and "fix" it, potentially introducing an actual bug in the process.

*Why this happens:* The agent's training optimized for helpful, agreeable responses. Disagreeing with the user is a pattern that was likely penalized during training. So the agent's prior is to agree.

*Detection strategy:* Be suspicious when the agent agrees with you too quickly on something non-trivial. Test it: deliberately suggest a bad approach and see if the agent pushes back. If it doesn't, you know to discount its agreement signals.

**Fixation loops - stuck and getting worse:**

You tell the agent to fix a bug. It changes something. The bug persists. You tell it again. It changes something else. The original change was wrong but it doesn't revert it - it adds a second change. Now there are two bugs. This can repeat 5-10 times until the code is unrecognizable and worse than when you started.

*When fixation loops happen:*
- The agent's approach is fundamentally wrong but it's making surface-level corrections
- The agent doesn't have enough context to understand the real problem
- The error message the agent is working from is misleading

*Detection strategy:* Count the iterations. If the agent hasn't fixed a bug in 2-3 attempts, stop. The approach is wrong. Either provide more context, reframe the problem, or solve it yourself. Do not let the agent iterate beyond 3 failed attempts - each iteration makes the code harder to recover.

**The "confident 10-year-old" problem:**

Agent-generated code is always formatted perfectly. It has comments. It uses good variable names. It follows the conventions of whatever language it's in. This surface-level professionalism makes it *feel* trustworthy - and that feeling is the most dangerous thing about working with agents.

A junior human developer's code *looks* junior. It has bad variable names, inconsistent formatting, missing comments. These visual cues tell you to review carefully. Agent code has none of these cues. It looks like it was written by a senior developer, even when the logic is wrong. You must develop the discipline to review agent code as carefully as you'd review the most junior developer's code, despite it looking like the most senior developer wrote it.

**Exercise - Failure Mode Scavenger Hunt:**
Use an agent to build a small but non-trivial feature (e.g., a caching layer with TTL expiration, or a rate limiter). Deliberately don't specify edge cases. Then systematically check:
1. What did it hallucinate? (APIs, functions, behaviors that don't exist)
2. Where did it make assumptions you didn't specify? (List every decision it made without being told)
3. What happens at the boundaries? (Empty input, maximum input, concurrent access, zero TTL, negative values)
4. If you introduce a bug, does it sycophantically agree with your wrong diagnosis?

**Key intuition to develop:** Agent output quality is bimodal - it's either quite good or completely wrong, with very little in between. And the surface appearance gives you no signal about which mode you're in. You must verify independently.`,
        },
      ],
    },
    {
      id: "3",
      title: "The Accountable Human",
      sections: [
        {
          id: "3.1",
          title: "Specification as the Primary Skill",
          key_intuition:
            "",
          markdown: `In the pre-agent era, specification was optional - you could iterate toward the right thing through code. In the agent era, specification is the primary tool of production. If you can't specify it precisely, you can't get it built correctly.

**The anatomy of a good specification:**

A specification that an agent can execute and a human can verify has five parts:
1. **Context:** What exists already, what constraints are in place, what the user expects. This is what the agent needs to make correct decisions about things you don't explicitly state.
2. **Requirements:** What the software must do, stated in terms that are testable. "Fast" is not testable. "Responds in under 200ms at p95 for 1000 concurrent users" is testable.
3. **Data model:** What entities exist, what their fields are, what the relationships between them are, what the constraints on the data are. This is the single most important section - agents make the most damaging errors when the data model is ambiguous.
4. **Error behavior:** What happens when things go wrong. If you don't specify this, the agent will either ignore errors or handle them in ways that hide problems. Specify: what errors are possible, what the user should see, what should be logged, whether the operation should retry.
5. **Acceptance criteria:** How you will verify this is done. Written *before* the agent starts, not after. These become your test cases.

**The discipline of "spec first":**
Write the specification before you open the agent. This is hard because the agent is right there, ready to go, and you think you know what you want. But "I know what I want" is a feeling, and feelings produce ambiguous specifications. Writing forces you to confront the things you haven't decided.

Common things you discover while writing a spec that you thought you already knew:
- What happens when the user does this action twice?
- Which fields are required vs. optional, and what are the defaults?
- Who can see this data? Who can modify it?
- What's the maximum size of this list/string/file?
- What happens to existing data when this feature ships?

**Exercise - Specification Stress Test:**
Write a specification for a feature (e.g., "user can upload a profile photo"). Then have a colleague - or an agent playing devil's advocate - ask you 20 questions about it. Questions like: "What image formats are supported? What's the max file size? What happens if the upload is interrupted? Where is the image stored? Is there a default? Can they delete it? What resolution? Does it get resized? Is there content moderation? What if they upload something that isn't an image?" Every question you can't immediately answer is a gap in your specification that the agent will fill with a guess.`,
        },
        {
          id: "3.2",
          title: "Verification and Evaluation",
          key_intuition:
            "",
          markdown: `You will spend more time verifying agent-generated code than you would have spent writing it manually. This is not a failure of the process - it IS the process. The agent's value is that it generates *candidates* faster than you could. Your value is that you *evaluate* those candidates with judgment the agent lacks.

**The verification hierarchy:**
Not all verification is equal. Arrange your verification effort from cheapest to most expensive:

1. **Static analysis and linting:** Does the code follow language rules, type constraints, and style conventions? Automated. The agent should produce code that passes these by default - if it doesn't, that's a red flag.
2. **Test execution:** Do the tests pass? Automated, but only as good as the tests. Remember: the agent may have written the tests too, and they may be testing the wrong things.
3. **Test evaluation:** Do the tests actually verify the requirements? Manual. Read each test and ask: "If this test passes, does it prove the requirement is met? What scenarios aren't covered?"
4. **Code review:** Is the implementation correct, secure, and maintainable? Manual. This is the core of pilotry - reading code you didn't write and evaluating it against your specification and your knowledge of the system.
5. **Integration testing:** Does this work correctly with the rest of the system? Semi-automated. The agent generated a component; you must verify it integrates correctly with everything it wasn't shown.
6. **Adversarial testing:** What happens when someone tries to break this? Manual. Send unexpected inputs, simulate failures, test edge cases the specification didn't cover.

**What to look for in code review of agent output:**

*Correctness:* Does the code actually do what the spec says? Not "does it look like it does" - trace the actual execution path for key scenarios.

*Hidden assumptions:* What is the code assuming about its environment that isn't guaranteed? Common: assuming a directory exists, assuming a network call will succeed, assuming data fits in memory, assuming a field is always present.

*Error handling honesty:* Does the error handling actually handle the error, or does it catch the exception and ignore it? Agents love \`catch (e) { console.log(e) }\` - which is worse than no error handling because it swallows the error silently.

*Unnecessary complexity:* Agents over-engineer. They add abstraction layers, factory patterns, and configuration options that nobody asked for. Every unnecessary abstraction is a maintenance burden and a place where bugs can hide. If the spec says "store data in a file," and the agent built a pluggable storage abstraction with a file backend, that's a problem.

**Exercise - Calibrated Review:**
Have an agent generate a feature. Before you review the code, write down your predictions: "I expect to find at least N issues of type X." Then review and compare. This calibration exercise builds your intuition for how much review effort different types of agent output require.`,
        },
        {
          id: "3.3",
          title: "Judgment Under Uncertainty",
          key_intuition:
            "",
          markdown: `The hardest skill in pilotry is knowing when to trust the agent and when to verify. You can't verify everything - you'd be slower than writing it yourself. You can't trust everything - you'd be shipping bugs and vulnerabilities. The skill is calibration.

**The trust framework:**

*High trust (spot-check):* The task is well-defined, the pattern is common, and the consequences of a bug are low. Example: generating a CRUD endpoint for a non-sensitive data type with standard validation.

*Medium trust (thorough review):* The task involves business logic, data transformation, or anything where "almost right" is wrong. Example: calculating pricing, applying discount rules, generating reports.

*Low trust (verify everything):* The task involves security, financial transactions, data deletion, or anything where a bug has severe consequences. Example: authentication flows, payment processing, data migration.

*Zero trust (do it yourself):* The task requires deep understanding of undocumented system behavior, involves subtle timing or ordering requirements, or the agent has already failed on it twice. Example: debugging a race condition, writing a database migration for a critical table with millions of rows.

**The cost model:**
Every piece of agent-generated code has a *verification cost* and a *failure cost*. Verification cost = time to check it thoroughly. Failure cost = consequences if a bug ships. Rational pilotry means: verify when failure cost > verification cost. Skip verification when failure cost < verification cost. The mistake new pilots make is treating all code as equal - they either verify everything (too slow) or nothing (too dangerous).

**Recognizing the intervention moment:**
The moment you realize the agent is going down the wrong path, you have three options:
1. **Redirect:** Provide more context or constraints. Works when the agent's approach is close but off.
2. **Reset:** Throw away the agent's output and start a new session with a better specification. Works when the approach is fundamentally wrong.
3. **Take the controls:** Write the code yourself. Works when the task requires judgment the agent doesn't have.

The mistake is option 4: **keep asking the agent to fix its own wrong approach.** This is the fixation loop from 2.3, and it always makes things worse.

**Exercise - Judgment Calibration:**
Over the course of a week, log every time you accept agent output and every time you reject it. For each, note: what was the task? What was your trust level? Did you verify? If you accepted without verifying, did it turn out to be correct? Build your personal dataset of "what I can trust agents with" vs. "what I must verify."`,
        },
        {
          id: "3.4",
          title: "Professional Practice",
          key_intuition:
            "You are not the person who uses the tool. You are the person who is responsible for the outcome. The tool's confidence is not your confidence. The tool's speed is not your speed. Your speed is measured in correct, secure, verified software - and that's the only speed that matters.",
          markdown: `Being a software pilot is not just a technical role - it's a professional practice with ethical weight.

**The accountability chain:**
When you ship agent-generated code, you are making a professional claim: "I have reviewed this code and I believe it is fit for purpose." This is the same claim a structural engineer makes when signing off on a building plan. The fact that an agent generated the code does not diminish your responsibility - it increases it, because the generator has no accountability, no license to revoke, no reputation to protect.

**Documenting "why":**
The pilot's audit trail is not the code - the agent generated that. The audit trail is the specification, the review notes, and the decision log. When something goes wrong in six months and someone asks "why was it built this way?", the answer must be findable. Document:
- Why you chose this approach over alternatives
- What you verified and what you chose to trust
- What constraints you gave the agent and why
- What the agent got wrong that you corrected

**Communicating with non-technical stakeholders:**
Your manager or client doesn't care that an agent generated the code. They care that it works, it's secure, and it's maintainable. When you say "the agent built it," you're undermining confidence without adding information. When you say "I specified, reviewed, and verified it - and here's the test plan that proves it meets requirements," you're demonstrating professionalism.

**Continuous learning:**
Agent capabilities change quarterly. What required zero trust six months ago might be high trust today. What agents couldn't do at all might be routine now. The pilot's learning is never done - and the most important learning is updating your trust calibration based on new evidence, not staying fixed on "agents can't do X" when they've gotten better, or "agents handle Y fine" when a new failure mode has emerged.

**Key intuition to develop:** You are not the person who uses the tool. You are the person who is responsible for the outcome. The tool's confidence is not your confidence. The tool's speed is not your speed. Your speed is measured in correct, secure, verified software - and that's the only speed that matters.`,
        },
      ],
    },
  ],
};
