import type { SectionLearningMap } from "../../../curricula";

export const map: SectionLearningMap = {
  "section_id": "3.4",
  "generated_at": "2024-07-25T10:30:00Z",
  "model_used": "gemini-2.0-flash",
  "prerequisites": [],
  "core_claims": [
    {
      "id": "claim-1",
      "statement": "Engineers can design and implement a 'pilot-per-feature' workflow for integrating agent-generated code, where one engineer owns the feature end-to-end, including specification, delegation, review, integration, and verification.",
      "concepts": [
        "Team workflows for agent-generated output"
      ],
      "demonstration_criteria": "Given a feature specification, the engineer can describe the steps they would take to delegate tasks to an agent, review the agent's output, and integrate the resulting code, outlining potential challenges and mitigation strategies."
    },
    {
      "id": "claim-2",
      "statement": "Engineers can apply code review protocols tailored for agent-generated code, accounting for the absence of an author to question and the lack of incremental trust.",
      "concepts": [
        "Code review protocols - what changes",
        "No author to question",
        "No incremental trust"
      ],
      "demonstration_criteria": "Given an agent-generated pull request, the engineer can identify at least three specific review considerations that differ from reviewing human-authored code, explaining why each consideration is important."
    },
    {
      "id": "claim-3",
      "statement": "Engineers can detect and address over-engineering in agent-generated code by identifying unnecessary abstractions and simplifying the implementation.",
      "concepts": [
        "Over-engineering detection"
      ],
      "demonstration_criteria": "Given an agent-generated code snippet, the engineer can identify instances of over-engineering, explain why they are problematic, and propose simplified alternatives that achieve the same functionality with less complexity."
    },
    {
      "id": "claim-4",
      "statement": "Engineers can use the 'generated by' signal to apply agent-specific review criteria, such as checking for hallucinated APIs and verifying edge case handling.",
      "concepts": [
        "The \"generated by\" signal"
      ],
      "demonstration_criteria": "Given an agent-generated pull request labeled as such, the engineer can demonstrate how they would specifically check for hallucinated APIs and verify edge case handling, providing examples of potential issues and how to detect them."
    },
    {
      "id": "claim-5",
      "statement": "Engineers can design and implement an incident response plan that addresses incidents originating from agent-generated code, focusing on systemic learning and process improvement.",
      "concepts": [
        "Incident response when the agent was the author"
      ],
      "demonstration_criteria": "Given a hypothetical incident caused by agent-generated code, the engineer can outline the steps they would take to investigate the incident, identify contributing factors related to the agent's involvement, and propose changes to the development process to prevent similar incidents in the future."
    },
    {
      "id": "claim-6",
      "statement": "Engineers can implement a 'pilot-pair' model to mitigate 'sycophancy drift' by having a second engineer review agent output against the original specification without seeing the agent interaction.",
      "concepts": [
        "Team workflows for agent-generated output"
      ],
      "demonstration_criteria": "Given a feature specification and agent-generated code, the engineer can, acting as the second reviewer in a 'pilot-pair' model, identify discrepancies between the specification and the code that the original pilot might have missed due to 'sycophancy drift'."
    }
  ],
  "key_misconceptions": [
    {
      "id": "misconception-1",
      "belief": "Agent-generated code requires less rigorous review than human-authored code because agents are inherently more precise.",
      "correction": "Agent-generated code requires different review criteria, focusing on hallucinated APIs, over-engineering, and edge case handling. The absence of author intent necessitates a thorough specification-based review.",
      "related_claims": [
        "claim-2",
        "claim-4"
      ]
    },
    {
      "id": "misconception-2",
      "belief": "If an agent wrote a bug, it's solely the agent's fault, and the solution is to use a different agent or prompt.",
      "correction": "Bugs in agent-generated code often indicate process failures in specification, verification, or risk assessment. The focus should be on improving these processes to prevent similar issues.",
      "related_claims": [
        "claim-5"
      ]
    }
  ],
  "key_intuition_decomposition": [
    {
      "id": "insight-1",
      "statement": "Integrating agents into workflows requires a shift from individual coding to process architecture, where the focus is on designing robust systems for specification, delegation, review, and verification.",
      "order": 1
    },
    {
      "id": "insight-2",
      "statement": "Code review for agent-generated code needs to adapt to the unique characteristics of agent output, such as the lack of author intent and the potential for over-engineering.",
      "order": 2
    },
    {
      "id": "insight-3",
      "statement": "Incident response for agent-generated code should prioritize systemic learning and process improvement over individual blame, focusing on identifying and addressing weaknesses in the development pipeline.",
      "order": 3
    }
  ]
};
