import type { SectionLearningMap } from "../../../curricula";

export const map: SectionLearningMap = {
  "section_id": "1.1",
  "generated_at": "2024-10-27T14:35:00Z",
  "model_used": "gemini-2.0-flash",
  "prerequisites": [],
  "core_claims": [
    {
      "id": "claim-1",
      "statement": "Code that compiles and passes tests is not necessarily correct, especially when dealing with concurrency or resource management.",
      "concepts": [
        "The gap between \"works\" and \"correct\"",
        "Concurrency - the agent's blind spot",
        "Memory and resource management"
      ],
      "demonstration_criteria": "Can identify at least three potential failure scenarios in agent-generated code that passes all provided tests, focusing on concurrency issues, resource leaks, or unexpected input."
    },
    {
      "id": "claim-2",
      "statement": "Agents often fail to account for concurrency issues, leading to race conditions and deadlocks in seemingly correct code.",
      "concepts": [
        "Concurrency - the agent's blind spot"
      ],
      "demonstration_criteria": "Can diagnose a concurrency bug (e.g., race condition, deadlock) in a Go program generated by an agent that uses goroutines and channels, and propose a fix using appropriate synchronization primitives."
    },
    {
      "id": "claim-3",
      "statement": "Agents may introduce memory and resource leaks, even in garbage-collected languages, due to improper handling of connections or file handles.",
      "concepts": [
        "Memory and resource management"
      ],
      "demonstration_criteria": "Can identify a resource leak (e.g., unclosed database connection, file handle) in agent-generated code, even if the code includes error handling, and explain how to fix it by ensuring proper resource cleanup in all execution paths."
    },
    {
      "id": "claim-4",
      "statement": "Pilotry requires proactively identifying potential failure modes beyond the scope of existing tests, especially related to concurrency, resource limits, and unexpected external dependencies.",
      "concepts": [
        "The gap between \"works\" and \"correct\""
      ],
      "demonstration_criteria": "Given a web application generated by an agent with 95% test coverage, can design and implement three new test cases that expose potential bugs related to concurrent access, database slowdown, or unexpected API responses."
    }
  ],
  "key_misconceptions": [
    {
      "id": "misconception-1",
      "belief": "If code compiles and passes all tests, it is production-ready.",
      "correction": "Passing tests is a necessary but not sufficient condition for production readiness. Pilotry requires proactively identifying and mitigating potential failure modes not covered by existing tests.",
      "related_claims": [
        "claim-1",
        "claim-4"
      ]
    },
    {
      "id": "misconception-2",
      "belief": "Async/await automatically makes JavaScript code thread-safe.",
      "correction": "Async/await does not guarantee thread safety. Shared mutable state accessed within async functions still requires explicit synchronization mechanisms to prevent race conditions.",
      "related_claims": [
        "claim-2"
      ]
    }
  ],
  "key_intuition_decomposition": [
    {
      "id": "insight-1",
      "statement": "Testing primarily validates expected behavior; pilotry focuses on anticipating and preventing unexpected behavior.",
      "order": 1
    },
    {
      "id": "insight-2",
      "statement": "Agents optimize for explicit constraints (tests, prompts), while pilotry requires considering implicit constraints (concurrency, resource limits).",
      "order": 2
    }
  ]
};
