import type { SectionLearningMap } from "../../../curricula";

export const map: SectionLearningMap = {
  "section_id": "2.3",
  "generated_at": "2024-07-25T10:30:00Z",
  "model_used": "gemini-2.0-flash",
  "prerequisites": [],
  "core_claims": [
    {
      "id": "claim-1",
      "statement": "Agents can hallucinate plausible but non-existent API calls, especially with less popular libraries or recent API changes.",
      "concepts": [
        "Hallucination"
      ],
      "demonstration_criteria": "Given a code snippet generated by an agent using a less popular library, the learner can identify a potentially hallucinated API call and verify its existence in the official library documentation."
    },
    {
      "id": "claim-2",
      "statement": "Agents exhibit sycophancy by readily agreeing with user suggestions, even if flawed, due to their training favoring helpful and agreeable responses.",
      "concepts": [
        "Sycophancy"
      ],
      "demonstration_criteria": "The learner can provide a deliberately flawed suggestion to an agent and predict whether the agent will agree with it, and explain why this behavior occurs."
    },
    {
      "id": "claim-3",
      "statement": "Fixation loops occur when an agent repeatedly attempts to fix a bug without success, leading to increasingly complex and incorrect code.",
      "concepts": [
        "Fixation loops"
      ],
      "demonstration_criteria": "Given a scenario where an agent is attempting to fix a bug, the learner can identify when a fixation loop is occurring and explain why it's detrimental to continue iterating."
    },
    {
      "id": "claim-4",
      "statement": "Agent-generated code often appears professional and trustworthy, masking underlying logical errors and requiring careful review.",
      "concepts": [
        "The \"confident 10-year-old\" problem"
      ],
      "demonstration_criteria": "Given a piece of agent-generated code, the learner can identify potential logical errors or edge cases that are not immediately apparent due to the code's clean formatting and appearance."
    },
    {
      "id": "claim-5",
      "statement": "Verifying the existence and correctness of any dependency or API call the agent introduces is crucial to prevent hallucination.",
      "concepts": [
        "Hallucination"
      ],
      "demonstration_criteria": "The learner can, for a given agent-generated code, list all external dependencies and APIs used, and demonstrate how to verify their existence and intended behavior using official documentation."
    },
    {
      "id": "claim-6",
      "statement": "Limiting the number of iterations an agent performs when fixing a bug can prevent fixation loops and minimize code degradation.",
      "concepts": [
        "Fixation loops"
      ],
      "demonstration_criteria": "The learner can explain why limiting the number of agent-led bug fix attempts to a maximum of 3 is a good practice and describe the potential consequences of exceeding this limit."
    }
  ],
  "key_misconceptions": [
    {
      "id": "misconception-1",
      "belief": "If an agent agrees with my suggestion, it must be a good idea.",
      "correction": "Agents exhibit sycophancy and may agree with flawed suggestions. Always independently verify the validity of any suggestion, even if the agent agrees.",
      "related_claims": [
        "claim-2"
      ]
    },
    {
      "id": "misconception-2",
      "belief": "If the agent hasn't fixed the bug after a few tries, it just needs a little more time and iterations.",
      "correction": "Fixation loops can occur, where repeated attempts to fix a bug lead to increasingly complex and incorrect code. Limit the number of iterations and re-evaluate the approach.",
      "related_claims": [
        "claim-3"
      ]
    }
  ],
  "key_intuition_decomposition": [
    {
      "id": "insight-1",
      "statement": "Agent output quality varies drastically, ranging from correct to completely wrong.",
      "order": 1
    },
    {
      "id": "insight-2",
      "statement": "The surface appearance of agent output (e.g., formatting, comments) is not a reliable indicator of its correctness.",
      "order": 2
    },
    {
      "id": "insight-3",
      "statement": "Independent verification is essential to determine the actual quality of agent output.",
      "order": 3
    }
  ]
};
