import type { SectionLearningMap } from "../../../curricula";

export const map: SectionLearningMap = {
  "section_id": "3.2",
  "generated_at": "2024-10-27T14:32:00Z",
  "model_used": "gemini-2.0-flash",
  "prerequisites": [],
  "core_claims": [
    {
      "id": "claim-1",
      "statement": "The verification hierarchy prioritizes verification methods based on cost, starting with static analysis and linting as the cheapest and adversarial testing as the most expensive.",
      "concepts": [
        "The verification hierarchy",
        "Static analysis and linting",
        "Adversarial testing"
      ],
      "demonstration_criteria": "Can explain the order of the verification hierarchy and justify the placement of each method based on its cost and effectiveness in identifying different types of issues."
    },
    {
      "id": "claim-2",
      "statement": "Code review is a critical step in verifying agent-generated code, focusing on correctness, hidden assumptions, error handling honesty, and unnecessary complexity.",
      "concepts": [
        "Code review"
      ],
      "demonstration_criteria": "Given a code snippet generated by an agent, can identify at least three potential issues related to correctness, hidden assumptions, error handling, or unnecessary complexity."
    },
    {
      "id": "claim-3",
      "statement": "Test evaluation involves manually assessing whether existing tests adequately verify the requirements, identifying gaps in test coverage, and suggesting additional test cases.",
      "concepts": [
        "Test evaluation",
        "Test execution"
      ],
      "demonstration_criteria": "Given a set of requirements and corresponding tests (potentially agent-generated), can evaluate the tests to determine if they adequately cover the requirements and propose additional test cases to address any gaps."
    },
    {
      "id": "claim-4",
      "statement": "Integration testing is essential to ensure that agent-generated components work correctly with the rest of the system, requiring verification beyond the component's isolated functionality.",
      "concepts": [
        "Integration testing"
      ],
      "demonstration_criteria": "Given an agent-generated component and a description of its integration points with other system components, can design and execute integration tests to verify correct interaction and data flow."
    },
    {
      "id": "claim-5",
      "statement": "Adversarial testing involves actively attempting to break the code by providing unexpected inputs, simulating failures, and testing edge cases not explicitly covered in the specification.",
      "concepts": [
        "Adversarial testing"
      ],
      "demonstration_criteria": "Given a piece of agent-generated code, can devise and execute at least three adversarial test cases that attempt to expose vulnerabilities or unexpected behavior."
    },
    {
      "id": "claim-6",
      "statement": "Static analysis and linting tools can automatically detect code style violations, type errors, and potential bugs, providing a cost-effective first line of defense in code verification.",
      "concepts": [
        "Static analysis and linting"
      ],
      "demonstration_criteria": "Can configure and run a static analysis tool on agent-generated code and interpret the output to identify and fix code style violations, type errors, and potential bugs."
    }
  ],
  "key_misconceptions": [
    {
      "id": "misconception-1",
      "belief": "If the agent-generated code passes all the tests, it is guaranteed to be correct and secure.",
      "correction": "Passing tests is necessary but not sufficient. Tests may not cover all edge cases, hidden assumptions, or potential vulnerabilities. Thorough code review and adversarial testing are still essential.",
      "related_claims": [
        "claim-2",
        "claim-3",
        "claim-5"
      ]
    },
    {
      "id": "misconception-2",
      "belief": "Static analysis and linting are sufficient to ensure code quality and prevent all bugs.",
      "correction": "Static analysis and linting can catch many common errors, but they cannot detect all types of bugs, especially those related to logic, security vulnerabilities, or integration issues. They are a first step, not a complete solution.",
      "related_claims": [
        "claim-1",
        "claim-6"
      ]
    }
  ],
  "key_intuition_decomposition": [
    {
      "id": "insight-1",
      "statement": "Agent-generated code requires rigorous verification because agents prioritize speed of generation over correctness and completeness.",
      "order": 1
    },
    {
      "id": "insight-2",
      "statement": "Your expertise lies in evaluating the agent's output, identifying potential issues, and ensuring the code meets the required standards of correctness, security, and maintainability.",
      "order": 2
    },
    {
      "id": "insight-3",
      "statement": "The verification hierarchy provides a structured approach to allocate verification effort effectively, focusing on the most critical and cost-effective methods.",
      "order": 3
    }
  ]
};
