import type { SectionLearningMap } from "../../../curricula";

export const map: SectionLearningMap = {
  "section_id": "3.3",
  "generated_at": "2024-07-10T14:30:00Z",
  "model_used": "gemini-2.0-flash",
  "prerequisites": [],
  "core_claims": [
    {
      "id": "claim-1",
      "statement": "Engineers must calibrate their trust in AI agents based on the task's risk profile, using a trust framework to determine the appropriate level of verification.",
      "concepts": [
        "The trust framework",
        "Recognizing the intervention moment"
      ],
      "demonstration_criteria": "Can categorize different software engineering tasks (e.g., generating CRUD endpoints, implementing authentication flows, debugging race conditions) according to the trust framework's levels (high, medium, low, zero) and justify the assigned level based on potential failure costs."
    },
    {
      "id": "claim-2",
      "statement": "Rational pilotry involves weighing the verification cost against the failure cost of agent-generated code to decide whether to verify it.",
      "concepts": [
        "The cost model"
      ],
      "demonstration_criteria": "Can analyze a given code snippet generated by an AI agent, estimate the time required to thoroughly verify it (verification cost), and estimate the potential consequences if a bug ships (failure cost), then justify whether verification is necessary based on the cost model."
    },
    {
      "id": "claim-3",
      "statement": "When an AI agent goes down the wrong path, engineers must choose the appropriate intervention strategy: redirect, reset, or take the controls.",
      "concepts": [
        "Recognizing the intervention moment",
        "Redirect",
        "Reset",
        "Take the controls"
      ],
      "demonstration_criteria": "Given a scenario where an AI agent is generating incorrect or suboptimal code, can select the most appropriate intervention strategy (redirect, reset, or take the controls) and explain why that strategy is preferable to the others."
    },
    {
      "id": "claim-4",
      "statement": "Avoid the fixation loop by not repeatedly asking the agent to fix its own fundamentally flawed approach.",
      "concepts": [
        "Recognizing the intervention moment"
      ],
      "demonstration_criteria": "Can identify scenarios where repeatedly prompting an AI agent to correct its own flawed output is unproductive and explain why resetting or taking control is a more efficient approach."
    }
  ],
  "key_misconceptions": [
    {
      "id": "misconception-1",
      "belief": "All agent-generated code should be treated the same, either always verified or never verified.",
      "correction": "The level of verification should be based on the trust framework and the cost model, considering both verification cost and failure cost.",
      "related_claims": [
        "claim-1",
        "claim-2"
      ]
    }
  ],
  "key_intuition_decomposition": [
    {
      "id": "insight-1",
      "statement": "Trusting AI agents blindly can lead to bugs and vulnerabilities.",
      "order": 1
    },
    {
      "id": "insight-2",
      "statement": "Verifying everything an AI agent produces is too slow and inefficient.",
      "order": 2
    },
    {
      "id": "insight-3",
      "statement": "The key is to calibrate your trust based on the risk and potential impact of errors.",
      "order": 3
    }
  ]
};
