import type { SectionLearningMap } from "../../../curricula";

export const map: SectionLearningMap = {
  "section_id": "3.4",
  "generated_at": "2024-07-03T14:37:22Z",
  "model_used": "gemini-2.0-flash",
  "prerequisites": [],
  "core_claims": [
    {
      "id": "claim-1",
      "statement": "Software pilots are ultimately accountable for the code they ship, regardless of whether it was generated by an agent.",
      "concepts": [
        "The accountability chain"
      ],
      "demonstration_criteria": "Can explain the software pilot's role in the accountability chain and justify why agent-generated code does not absolve the pilot of responsibility, using an analogy to a structural engineer signing off on building plans."
    },
    {
      "id": "claim-2",
      "statement": "A software pilot's primary audit trail consists of specifications, review notes, and decision logs, which document the 'why' behind design and implementation choices.",
      "concepts": [
        "Documenting \"why\""
      ],
      "demonstration_criteria": "Given a scenario where a bug is discovered in previously shipped agent-generated code, can locate and explain the relevant design decisions from the specification, review notes, and decision logs."
    },
    {
      "id": "claim-3",
      "statement": "Software pilots should communicate the value they add (specification, review, verification) to non-technical stakeholders, rather than focusing on the agent's role in code generation.",
      "concepts": [
        "Communicating with non-technical stakeholders"
      ],
      "demonstration_criteria": "Can rephrase a statement about agent-generated code into a statement that highlights the pilot's contributions to a project's success, emphasizing specification, review, and verification processes."
    },
    {
      "id": "claim-4",
      "statement": "Software pilots must continuously update their understanding of agent capabilities and adjust their trust calibration based on new evidence.",
      "concepts": [
        "Continuous learning"
      ],
      "demonstration_criteria": "Can identify at least two recent advancements in agent capabilities and explain how these advancements might affect the pilot's workflow or trust assumptions."
    }
  ],
  "key_misconceptions": [
    {
      "id": "misconception-1",
      "belief": "If an agent generates the code, the software pilot is not responsible for any errors or bugs.",
      "correction": "The software pilot is always responsible for ensuring the code meets requirements and is fit for purpose, regardless of how it was generated.",
      "related_claims": [
        "claim-1"
      ]
    },
    {
      "id": "misconception-2",
      "belief": "The agent's output is the most important documentation of the software development process.",
      "correction": "The agent's output is only one part of the process. The pilot's specifications, review notes, and decision logs are the most important documentation.",
      "related_claims": [
        "claim-2"
      ]
    }
  ],
  "key_intuition_decomposition": [
    {
      "id": "insight-1",
      "statement": "Your primary responsibility is the quality and security of the final software product, not the efficiency of the tool used to create it.",
      "order": 1
    },
    {
      "id": "insight-2",
      "statement": "The confidence level of the AI tool should not dictate your own confidence in the software; independent verification is crucial.",
      "order": 2
    },
    {
      "id": "insight-3",
      "statement": "Your value as a software pilot lies in your ability to ensure correctness, security, and maintainability, not in how quickly the agent generates code.",
      "order": 3
    }
  ]
};
