import type { SectionLearningMap } from "../../curricula";

import { map as level_0_0_1 } from "./level-0/0.1";
import { map as level_0_0_2 } from "./level-0/0.2";
import { map as level_0_0_3 } from "./level-0/0.3";
import { map as level_0_0_4 } from "./level-0/0.4";
import { map as level_0_0_5 } from "./level-0/0.5";
import { map as level_0_0_6 } from "./level-0/0.6";
import { map as level_1_1_1 } from "./level-1/1.1";
import { map as level_1_1_2 } from "./level-1/1.2";
import { map as level_1_1_3 } from "./level-1/1.3";
import { map as level_1_2_1 } from "./level-1/2.1";
import { map as level_1_2_2 } from "./level-1/2.2";
import { map as level_1_2_3 } from "./level-1/2.3";
import { map as level_1_3_1 } from "./level-1/3.1";
import { map as level_1_3_2 } from "./level-1/3.2";
import { map as level_1_3_3 } from "./level-1/3.3";
import { map as level_1_3_4 } from "./level-1/3.4";
import { map as level_1_4_1 } from "./level-1/4.1";
import { map as level_1_5_1 } from "./level-1/5.1";
import { map as level_1_6_1 } from "./level-1/6.1";
import { map as level_10_1_1 } from "./level-10/1.1";
import { map as level_10_1_2 } from "./level-10/1.2";
import { map as level_10_1_3 } from "./level-10/1.3";
import { map as level_10_2_1 } from "./level-10/2.1";
import { map as level_10_2_2 } from "./level-10/2.2";
import { map as level_10_2_3 } from "./level-10/2.3";
import { map as level_10_3_1 } from "./level-10/3.1";
import { map as level_10_3_2 } from "./level-10/3.2";
import { map as level_10_3_3 } from "./level-10/3.3";
import { map as level_10_3_4 } from "./level-10/3.4";
import { map as level_10_4_1 } from "./level-10/4.1";
import { map as level_10_5_1 } from "./level-10/5.1";
import { map as level_10_6_1 } from "./level-10/6.1";
import { map as level_20_1_1 } from "./level-20/1.1";
import { map as level_20_1_2 } from "./level-20/1.2";
import { map as level_20_1_3 } from "./level-20/1.3";
import { map as level_20_2_1 } from "./level-20/2.1";
import { map as level_20_2_2 } from "./level-20/2.2";
import { map as level_20_2_3 } from "./level-20/2.3";
import { map as level_20_3_1 } from "./level-20/3.1";
import { map as level_20_3_2 } from "./level-20/3.2";
import { map as level_20_3_3 } from "./level-20/3.3";
import { map as level_20_3_4 } from "./level-20/3.4";
import { map as level_20_4_1 } from "./level-20/4.1";
import { map as level_20_5_1 } from "./level-20/5.1";
import { map as level_20_6_1 } from "./level-20/6.1";

/**
 * Registry of generated learning maps, keyed by "profile:sectionId".
 * Auto-generated by scripts/generate-learning-maps.ts - do not edit manually.
 */
export const learningMapRegistry = new Map<string, SectionLearningMap>();

learningMapRegistry.set("level-0:0.1", level_0_0_1);
learningMapRegistry.set("level-0:0.2", level_0_0_2);
learningMapRegistry.set("level-0:0.3", level_0_0_3);
learningMapRegistry.set("level-0:0.4", level_0_0_4);
learningMapRegistry.set("level-0:0.5", level_0_0_5);
learningMapRegistry.set("level-0:0.6", level_0_0_6);
learningMapRegistry.set("level-1:1.1", level_1_1_1);
learningMapRegistry.set("level-1:1.2", level_1_1_2);
learningMapRegistry.set("level-1:1.3", level_1_1_3);
learningMapRegistry.set("level-1:2.1", level_1_2_1);
learningMapRegistry.set("level-1:2.2", level_1_2_2);
learningMapRegistry.set("level-1:2.3", level_1_2_3);
learningMapRegistry.set("level-1:3.1", level_1_3_1);
learningMapRegistry.set("level-1:3.2", level_1_3_2);
learningMapRegistry.set("level-1:3.3", level_1_3_3);
learningMapRegistry.set("level-1:3.4", level_1_3_4);
learningMapRegistry.set("level-1:4.1", level_1_4_1);
learningMapRegistry.set("level-1:5.1", level_1_5_1);
learningMapRegistry.set("level-1:6.1", level_1_6_1);
learningMapRegistry.set("level-10:1.1", level_10_1_1);
learningMapRegistry.set("level-10:1.2", level_10_1_2);
learningMapRegistry.set("level-10:1.3", level_10_1_3);
learningMapRegistry.set("level-10:2.1", level_10_2_1);
learningMapRegistry.set("level-10:2.2", level_10_2_2);
learningMapRegistry.set("level-10:2.3", level_10_2_3);
learningMapRegistry.set("level-10:3.1", level_10_3_1);
learningMapRegistry.set("level-10:3.2", level_10_3_2);
learningMapRegistry.set("level-10:3.3", level_10_3_3);
learningMapRegistry.set("level-10:3.4", level_10_3_4);
learningMapRegistry.set("level-10:4.1", level_10_4_1);
learningMapRegistry.set("level-10:5.1", level_10_5_1);
learningMapRegistry.set("level-10:6.1", level_10_6_1);
learningMapRegistry.set("level-20:1.1", level_20_1_1);
learningMapRegistry.set("level-20:1.2", level_20_1_2);
learningMapRegistry.set("level-20:1.3", level_20_1_3);
learningMapRegistry.set("level-20:2.1", level_20_2_1);
learningMapRegistry.set("level-20:2.2", level_20_2_2);
learningMapRegistry.set("level-20:2.3", level_20_2_3);
learningMapRegistry.set("level-20:3.1", level_20_3_1);
learningMapRegistry.set("level-20:3.2", level_20_3_2);
learningMapRegistry.set("level-20:3.3", level_20_3_3);
learningMapRegistry.set("level-20:3.4", level_20_3_4);
learningMapRegistry.set("level-20:4.1", level_20_4_1);
learningMapRegistry.set("level-20:5.1", level_20_5_1);
learningMapRegistry.set("level-20:6.1", level_20_6_1);

/**
 * Look up a learning map by section ID.
 * Searches across all profiles, returning the first match.
 * For profile-specific lookup, use the registry directly with "profile:sectionId" key.
 */
export function getLearningMap(sectionId: string): SectionLearningMap | undefined {
  // First try direct lookup (for backward compat with bare section IDs)
  for (const [key, value] of learningMapRegistry) {
    if (key.endsWith(":" + sectionId)) {
      return value;
    }
  }
  return undefined;
}

/**
 * Look up a learning map by profile and section ID.
 */
export function getLearningMapForProfile(
  profile: string,
  sectionId: string,
): SectionLearningMap | undefined {
  return learningMapRegistry.get(profile + ":" + sectionId);
}
