import type { SectionLearningMap } from "../../../curricula";

export const map: SectionLearningMap = {
  "section_id": "3.2",
  "generated_at": "2024-10-27T14:32:00Z",
  "model_used": "gemini-2.0-flash",
  "prerequisites": [],
  "core_claims": [
    {
      "id": "claim-1",
      "statement": "A healthy engineering culture in the age of AI agents prioritizes understanding agent output, and engineers should feel safe admitting when they don't understand the code generated by agents.",
      "concepts": [
        "The most important sentence in the new paradigm"
      ],
      "demonstration_criteria": "Can describe a scenario where an engineer expresses a lack of understanding of agent-generated code and explain how a supportive response from leadership would differ from an unsupportive one, including the potential consequences of each."
    },
    {
      "id": "claim-2",
      "statement": "Incentive structures must be adjusted to prioritize verification rigor over output volume to ensure the quality and reliability of agent-generated code.",
      "concepts": [
        "Incentive structures"
      ],
      "demonstration_criteria": "Can compare two performance review systems, one that rewards output volume and one that rewards verification rigor, and explain how each system would impact the behavior of engineers working with AI agents."
    },
    {
      "id": "claim-3",
      "statement": "Organizations must actively combat the pressure to ship faster by emphasizing that speed without verification increases the risk of production incidents when using AI agents.",
      "concepts": [
        "Fighting the pressure to ship faster"
      ],
      "demonstration_criteria": "Given a scenario where leadership is pushing for faster feature releases using AI agents, can construct an argument, using the auto-pilot analogy, that explains why verification is crucial and how inadequate verification can lead to costly incidents."
    },
    {
      "id": "claim-4",
      "statement": "Incident reviews should explicitly assess whether the team understood the code they shipped, especially when involving agent-generated code, to identify process gaps rather than assigning blame.",
      "concepts": [
        "The most important sentence in the new paradigm"
      ],
      "demonstration_criteria": "Given a hypothetical incident caused by agent-generated code, can outline the key questions that should be asked during the incident review to determine if a lack of understanding contributed to the incident, and explain how the findings should be used to improve processes."
    },
    {
      "id": "claim-5",
      "statement": "Team metrics should incorporate defect escape rate alongside throughput to provide a more comprehensive view of team performance in the age of AI agents.",
      "concepts": [
        "Incentive structures"
      ],
      "demonstration_criteria": "Can explain how tracking defect escape rate, in addition to throughput, can help identify teams that are prioritizing speed over quality when using AI agents, and suggest strategies for addressing this imbalance."
    }
  ],
  "key_misconceptions": [
    {
      "id": "misconception-1",
      "belief": "AI agents automate coding, so verification is less important.",
      "correction": "AI agents automate code generation, but verification becomes MORE important to catch errors and ensure understanding. Without verification, the risk of incidents increases.",
      "related_claims": [
        "claim-3"
      ]
    },
    {
      "id": "misconception-2",
      "belief": "Increased velocity with AI agents automatically translates to increased value.",
      "correction": "Increased velocity only translates to increased value if the output is verified and of high quality. Unverified output can lead to costly incidents and decreased value.",
      "related_claims": [
        "claim-2"
      ]
    }
  ],
  "key_intuition_decomposition": [
    {
      "id": "insight-1",
      "statement": "The core challenge is ensuring human understanding and verification of agent-generated code.",
      "order": 1
    },
    {
      "id": "insight-2",
      "statement": "Traditional incentives focused on output volume can undermine the necessary verification processes.",
      "order": 2
    },
    {
      "id": "insight-3",
      "statement": "The pressure to ship faster, amplified by the perceived speed of AI agents, can lead to skipped verification steps and increased risk.",
      "order": 3
    }
  ]
};
